services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - maven_settings
    container_name: ruleengine-app
    mem_limit: 512m
    mem_reservation: 256m
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
      RULEENGINE_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres?currentSchema=ruleengine
    networks:
      - local_network

networks:
  local_network:
    external: true

secrets:
  maven_settings:
    file: ${M2_HOME}/settings.xml