server:
  port: ${PORT:8080}
  servlet:
    context-path: /ruleengine

spring:
  application:
    name: ruleengine

  devtools:
    add-properties: true

  datasource:
    url: ${RULEENGINE_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=ruleengine}
    username: ${RULEENGINE_DATASOURCE_USERNAME:postgres}
    password: ${RULEENGINE_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        generate_statistics: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: ruleengine
    default-schema: ruleengine

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB